/**
 * All available movement types:
 * * `ATTACK` - MISSING DETAIL INFO
 * * `DEFENCE` - MISSING DETAIL INFO
 * * `TRAVEL` - MISSING DETAIL INFO
 * * `SPY` - MISSING DETAIL INFO
 * * `MARKET` - MISSING DETAIL INFO
 * * `CONQUER` - MISSING DETAIL INFO
 * * `TREASUREHUNT` - MISSING DETAIL INFO
 * * `SHADOWATTACK` - MISSING DETAIL INFO
 * * `SHADOWTRAVEL` - MISSING DETAIL INFO
 * * `KINGDOM_GOODTRANSER` - MISSING DETAIL INFO
 * * `KINGDOM_UNIT_TRANSFER` - MISSING DETAIL INFO
 * * `NPC_ATTACK` - MISSING DETAIL INFO
 * * `SEASON_GOODSTRAVEL` - MISSING DETAIL INFO
 * * `SEASON_UNITTRAVEL` - MISSING DETAIL INFO
 * * `PLAGUEMONK` - MISSING DETAIL INFO
 * * `CONQUER_FACTION` - MISSING DETAIL INFO
 * * `ALIEN_ATTACK` - MISSING DETAIL INFO
 * * `FACTION_ATTACK` - MISSING DETAIL INFO
 * * `ALLIANCE_CAMP_TAUNT_ATTACK` - MISSING DETAIL INFO
 * * `ALLIANCE_CAMP_ATTACK` - MISSING DETAIL INFO
 * * `SHAPESHIFTER_CAMP_ATTACK` - MISSING DETAIL INFO
 * * `COLLECTOR_ATTACK` - MISSING DETAIL INFO
 * * `TEMP_SERVER_COLLECTOR_ATTACK` - MISSING DETAIL INFO
 * * `TEMP_SERVER_RANKSWAP_ATTACK` - MISSING DETAIL INFO
 * * `DAIMYO_TOWNSHIP_DEFENSE` - MISSING DETAIL INFO
 * * `DAIMYO_TAUNT_ATTACK` - MISSING DETAIL INFO
 * * `DAIMYO_CASTLE_ATTACK` - MISSING DETAIL INFO
 * * `ALLIANCE_BATTLE_GROUND_COLLECTOR_ATTACK` - MISSING DETAIL INFO
 * * `CHARGE_CAMP_ATTACK` - MISSING DETAIL INFO
 * * `TEMP_SERVER_CHARGE_ATTACK` - MISSING DETAIL INFO
 * * `ALLIANCE_BATTLE_GROUND_ALLIANCE_TOWER_DEFENSE` - MISSING DETAIL INFO
 * * `ALLIANCE_BATTLE_GROUND_ALLIANCE_TOWER_ATTACK` - MISSING DETAIL INFO
 * @typedef {string} MovementType
 */
const MovementTypes = {
    'ATTACK': 0,
    'DEFENCE': 1,
    'TRAVEL': 2,
    'SPY': 3,
    'MARKET': 4,
    'CONQUER': 5,
    'TREASUREHUNT': 6,
    'SHADOWATTACK': 7,
    'SHADOWTRAVEL': 8,
    'KINGDOM_GOODTRANSER': 9,
    'KINGDOM_UNIT_TRANSFER': 10,
    'NPC_ATTACK': 11,
    'SEASON_GOODSTRAVEL': 12,
    'SEASON_UNITTRAVEL': 13,
    'PLAGUEMONK': 14,
    'CONQUER_FACTION': 15,
    'ALIEN_ATTACK': 17,
    'FACTION_ATTACK': 18,
    'ALLIANCE_CAMP_TAUNT_ATTACK': 20,
    'ALLIANCE_CAMP_ATTACK': 21,
    'SHAPESHIFTER_CAMP_ATTACK': 22,
    'COLLECTOR_ATTACK': 23,
    'TEMP_SERVER_COLLECTOR_ATTACK': 24,
    'TEMP_SERVER_RANKSWAP_ATTACK': 25,
    'DAIMYO_TOWNSHIP_DEFENSE': 26,
    'DAIMYO_TAUNT_ATTACK': 27,
    'DAIMYO_CASTLE_ATTACK': 28,
    'ALLIANCE_BATTLE_GROUND_COLLECTOR_ATTACK': 29,
    'CHARGE_CAMP_ATTACK': 30,
    'TEMP_SERVER_CHARGE_ATTACK': 31,
    'ALLIANCE_BATTLE_GROUND_ALLIANCE_TOWER_DEFENSE': 32,
    'ALLIANCE_BATTLE_GROUND_ALLIANCE_TOWER_ATTACK': 33
}

exports.Events = {
    MOVEMENT_NEW: "movementAdd",
    MOVEMENT_ADD: "movementAdd",
    MOVEMENT_UPDATE: "movementUpdate",
}